from .aperture import Aperture
from .decenterable import Decenterable
from .obscurable import Obscurable
from .circular import Circular
from .polygon import Polygon
from .rectangular import Rectangular
from .spider import Spider
from .regular_polygon import RegularPolygon
from .general_polygon import GeneralPolygon
from .isosceles_trapezoid import IsoscelesTrapezoid
from .asymmetric_rectangular import AsymmetricRectangular
