name: kgpy-env
channels:
  - conda-forge
dependencies:
  - python >= 3.7
  - pytest
  - numpy >= 1.18
  - matplotlib
  - scipy
  - astropy
  - shapely
  - pythonocc-core
  - sphinx-autodoc-typehints
  - sphinx_rtd_theme