package:
  name: kgpy
  version: 0.0.1

source:
  git_url: https://github.com/Kankelborg-Group/kgpy.git
  git_depth: 1

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python >= 3.7
    - pytest
    - numpy >= 1.18
    - matplotlib
    - scipy
    - astropy
    - shapely
    - pythonocc-core
