# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: kgpy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.7, 3.8]
    name: ${{ matrix.os}}, Python ${{ matrix.python-version }} lint and test
    steps:
      - uses: actions/checkout@v2
#      - name: Cache conda
#        uses: actions/cache@v1
#        env:
#          # Increase this value to reset cache if etc/example-environment.yml has not changed
#          CACHE_NUMBER: 0
#        with:
#          path: ~/conda_pkgs_dir
#          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('etc/example-environment.yml') }}
      - uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: github_env
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
      - name: Install base dependencies
        shell: bash -l {0}
        run: conda install conda-build flake8 pytest
      - name: Install project
        shell: bash -l {0}
        run: conda develop .
#      - name: Lint with flake8
#        run: |
#          # stop the build if there are Python syntax errors or undefined names
#          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        shell: bash -l {0}
        run: pytest