
name: tests

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019, macOS-latest]
        python-version: [3.8, 3.9]
    name: ${{ matrix.os }}, Python ${{ matrix.python-version }} lint and test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: If Windows, define HOME environment variable for chianti compatibility
        if: runner.os == 'Windows'
        run: |
          echo "HOME=$env:USERPROFILE" >> $env:GITHUB_ENV
      - name: Check HOME
        if: runner.os == 'Windows'
        run: |
          $env:HOME
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          pip install -e .
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true
